### PR TITLE
Update to Arrow 0.5.0 release

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@wesm AppVeyor still fails although `parquet-cpp` should be uptodate. I sadly have no idea on how debug this without having Windows.

**Comment by wesm** [comment]
Yikes. I will try to debug on my Windows machine later today

**Comment by wesm** [comment]
The reason for the failure is that the recent Snappy Windows update in conda-forge broke our toolchain. I'm investigating

**Comment by wesm** [comment]
Triggered build now that the updated arrow-cpp Windows build has made it through the tubes

**Comment by wesm** [comment]
Huzzah!

**Pull request merged**
