### PR TITLE
update to 0.2.0

### PR DESCRIPTION
**Pull request by leifwalsh**

### CODE REVIEW

**Comment by leifwalsh** [comment]
Do we need to add a dependency on boost?

```sh
import: 'pyarrow'
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/pyarrow_1488056606594/test_tmp/run_test.py", line 27, in <module>
    import pyarrow
  File "/feedstock_root/build_artefacts/pyarrow_1488056606594/_t_env/lib/python2.7/site-packages/pyarrow/__init__.py", line 28, in <module>
    import pyarrow.config
ImportError: libboost_regex.so.1.63.0: cannot open shared object file: No such file or directory
TESTS FAILED: pyarrow-0.2.post-np111py27_0
```

**Comment by wesm** [comment]
Ah yes, Parquet now depends on libboost_regex (before it had header-only dependencies). This might be kind of a bummer but the right thing to do is to set `-DPARQUET_BOOST_USE_SHARED=off` in parquet-cpp so libboost_regex.a gets statically linked. The alternative is to make boost temporarily a runtime dependency 

https://github.com/apache/parquet-cpp/blob/master/CMakeLists.txt#L81

**Comment by wesm** [comment]
Pushed this directly https://github.com/conda-forge/parquet-cpp-feedstock/commit/7465661f6a861c267eb8afd8f78986a9f69b75e6 rather than going through the pull request business. if the build succeeds then we're back in business

**Comment by leifwalsh** [comment]
@wesm I can't trigger a rebuild for circleci I don't think.

**Comment by leifwalsh** [comment]
Travis said it accepted my rebuild request but it doesn't look like it did.  Other thing I could do is push another commit that makes us depend on at least build 14 of parquet but that seems weird.

**Comment by leifwalsh** [comment]
oh I think I can just make a new PR

**Pull request closed without merging**
