### PR TITLE
Take over pyarrow-* builds from arrow-cpp v16

### PR DESCRIPTION
**Pull request by h-vetinari**
For https://github.com/conda-forge/arrow-cpp-feedstock/issues/1381, cut out from https://github.com/conda-forge/arrow-cpp-feedstock/pull/1376, more precisely https://github.com/conda-forge/arrow-cpp-feedstock/commit/a66c7c666f1ca3ee1f4ffcf825e9f61d2d6bd77b

Closes https://github.com/conda-forge/arrow-cpp-feedstock/issues/1381

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/arrow-cpp, this is the implementation of https://github.com/conda-forge/arrow-cpp-feedstock/issues/1381. It basically takes over what we had in https://github.com/conda-forge/arrow-cpp-feedstock/pull/1376, only that I'm deduplicating the builds for `pyarrow{,-all,-tests}` between CUDA/non-CUDA, because that distinction only matters for `pyarrow-core`. As a nice side-effect also reduces artefact churn and build times. 🥳 

Given that the RFC received no opposition, I'm planning to merge this in 48h unless there are comments (or someone merges it earlier 🙃).

**Comment by raulcd** [comment]
I don't have permissions to re-run the failed job but this seems like a flaky as minio wasn't available for the S3 tests.
```
_______________________ ERROR at setup of test_read_s3fs _______________________

s3_connection = ('localhost', 52375, 'arrow', 'apachearrow')
tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x40002614ac20>, _basetemp=PosixPath('/tmp/pytest-of-conda/pytest-0'), _retention_count=3, _retention_policy='all'))
msg = 'Service Unavailable'
hdrs = <http.client.HTTPMessage object at 0x400024a36b30>

    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 503: Service Unavailable

../urllib/request.py:643: HTTPError
---------------------------- Captured stdout setup -----------------------------

API: SYSTEM()
Time: 05:11:27 UTC 05/08/2024
Error: Unable to listen on `[::1]:52375`: listen tcp [::1]:52375: bind: cannot assign requested address (*errors.errorString)
       4: internal/logger/logger.go:260:logger.LogIf()
       3: cmd/server-main.go:779:cmd.serverMain.func8.1.1()
       2: internal/http/server.go:98:http.(*Server).Init()
       1: cmd/server-main.go:778:cmd.serverMain.func8.1()

```

**Comment by xhochy** [comment]
New failure after restart:

```
2024-05-08T10:25:42.0499540Z pyarrow/tests/test_flight.py .....s.............s.....s...........s..... [ 75%]
2024-05-08T10:25:53.7858031Z ..ss.................ss.s....                                            [ 76%]
2024-05-08T10:25:54.1725673Z Fatal Python error: Aborted
2024-05-08T10:25:54.1726220Z 
2024-05-08T10:25:54.1764407Z Thread 0x00004000c24c6200 (most recent call first):
2024-05-08T10:25:54.1795176Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
2024-05-08T10:25:54.1800422Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 953 in run
2024-05-08T10:25:54.1801395Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2024-05-08T10:25:54.1802354Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 973 in _bootstrap
2024-05-08T10:25:54.1802721Z 
2024-05-08T10:25:54.1802897Z Thread 0x00004000c14c5200 (most recent call first):
2024-05-08T10:25:54.1803647Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
2024-05-08T10:25:54.1804589Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 953 in run
2024-05-08T10:25:54.1805521Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2024-05-08T10:25:54.1821049Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 973 in _bootstrap
2024-05-08T10:25:54.1821437Z 
2024-05-08T10:25:54.1821672Z Thread 0x00004000c04c4200 (most recent call first):
2024-05-08T10:25:54.1822433Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
2024-05-08T10:25:54.1823388Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 953 in run
2024-05-08T10:25:54.1824369Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2024-05-08T10:25:54.1825300Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 973 in _bootstrap
2024-05-08T10:25:54.1825776Z 
2024-05-08T10:25:54.1825951Z Thread 0x00004000bf4c3200 (most recent call first):
2024-05-08T10:25:54.1826701Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
2024-05-08T10:25:54.1827645Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 953 in run
2024-05-08T10:25:54.1828588Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2024-05-08T10:25:54.1829529Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 973 in _bootstrap
2024-05-08T10:25:54.1829877Z 
2024-05-08T10:25:54.1830060Z Thread 0x00004000abe4b200 (most recent call first):
2024-05-08T10:25:54.1830789Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
2024-05-08T10:25:54.1831822Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 953 in run
2024-05-08T10:25:54.1832777Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2024-05-08T10:25:54.1833723Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 973 in _bootstrap
2024-05-08T10:25:54.1845930Z 
2024-05-08T10:25:54.1846289Z Thread 0x00004000a254a200 (most recent call first):
2024-05-08T10:25:54.1847142Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/selectors.py", line 469 in select
2024-05-08T10:25:54.1848199Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/asyncio/base_events.py", line 1871 in _run_once
2024-05-08T10:25:54.1849262Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/asyncio/base_events.py", line 603 in run_forever
2024-05-08T10:25:54.1850478Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 953 in run
2024-05-08T10:25:54.1851952Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2024-05-08T10:25:54.1853068Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/threading.py", line 973 in _bootstrap
2024-05-08T10:25:54.1853627Z 
2024-05-08T10:25:54.1853887Z Thread 0x00004000012e7410 (most recent call first):
2024-05-08T10:25:54.1854740Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_callers.py", line 124 in _multicall
2024-05-08T10:25:54.1855820Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
2024-05-08T10:25:54.1856889Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
2024-05-08T10:25:54.1858117Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/_pytest/main.py", line 364 in pytest_runtestloop
2024-05-08T10:25:54.1859202Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
2024-05-08T10:25:54.1860285Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
2024-05-08T10:25:54.1861354Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
2024-05-08T10:25:54.1862412Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/_pytest/main.py", line 339 in _main
2024-05-08T10:25:54.1863611Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/_pytest/main.py", line 285 in wrap_session
2024-05-08T10:25:54.1864681Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/_pytest/main.py", line 332 in pytest_cmdline_main
2024-05-08T10:25:54.1865767Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_callers.py", line 103 in _multicall
2024-05-08T10:25:54.1866847Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_manager.py", line 120 in _hookexec
2024-05-08T10:25:54.1867906Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/pluggy/_hooks.py", line 513 in __call__
2024-05-08T10:25:54.1868981Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/_pytest/config/__init__.py", line 178 in main
2024-05-08T10:25:54.1870174Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.10/site-packages/_pytest/config/__init__.py", line 206 in console_main
2024-05-08T10:25:54.1871181Z   File "/home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/pytest", line 11 in <module>
2024-05-08T10:25:54.1871633Z 
2024-05-08T10:25:54.1945706Z Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pyarrow.lib, pyarrow._fs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, cython.cimports.libc.math, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, pandas._libs.hashingpyarrow/tests/test_flight_async.py ...                                   [ 76%]
2024-05-08T10:25:54.2123009Z , pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, fastparquet.cencoding, fastparquet.speedups, pyarrow.gandiva, pyarrow._acero, pyarrow._csv, pyarrow._json, pyarrow._dataset, pyarrow._dataset_orc, pyarrow._parquet, pyarrow._parquet_encryption, pyarrow._dataset_parquet_encryption, pyarrow._dataset_parquet, pyarrow._orc, pyarrow._flight, pyarrow._substrait, _cffi_backend, pyarrow._pyarrow_cpp_tests, pyarrow._feather, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, _brotli, multidict._multidict, yarl._quoting_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, frozenlist._frozenlist, extensions (total: 114)
2024-05-08T10:26:06.6769608Z /home/conda/feedstock_root/build_artifacts/apache-arrow_1715161497469/test_tmp/run_test.sh: line 9:  5499 Aborted                 (core dumped) pytest pyarrow/ -rfEs -k "not (_not_a_real_test or test_cuda or test_dlpack_cuda_not_supported or (test_csv and test_cancellation) or (test_flight and test_interrupt) or test_cython_api or test_visit_strings or test_debug_memory_pool_disabled or test_env_var_io_thread_count or (test_delete_dir and S3FileSystem) or (test_get_file_info and S3FileSystem) or (test_move_directory and S3FileSystem) or test_feather_format[serial])"
```

**Review by xhochy — APPROVED** [review]

**Comment by h-vetinari** [comment]
I keep repeating not to squash-merge my PRs. In this case I really want this fixed, so I'll forcepush main. GH changes the merge defaults based on logic that I don't understand, but if you push the button, it's your responsibility to choose the right one.

**Comment by xhochy** [comment]
> I keep asking not to squash-merge my PRs. In this case I really want this fixed, so I'll forcepush main. GH changes the merge defaults based on logic that I don't understand, but if you push the button, it's your responsibility to choose the right one.

Sorry about this. I always pick the default and I'm also against squash merges for my PRs. This was definitely not intentional!

**Pull request merged**
