### PR TITLE
Update to 0.5.0.pre against Arrow master

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@jakirkham @ocefpaf do you know what could be causing this linker failure? Perhaps I need to render all my feedstocks? 

```
+ source /Users/travis/miniconda3/bin/activate /Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/_t_env
+ /Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/_t_env/bin/python -s /Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/test_tmp/run_test.py
import: 'pyarrow'
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/test_tmp/run_test.py", line 2, in <module>
    import pyarrow
  File "/Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/_t_env/lib/python2.7/site-packages/pyarrow/__init__.py", line 32, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: dlopen(/Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/_t_env/lib/python2.7/site-packages/pyarrow/lib.so, 2): Symbol not found: __ZNSt3__1lsIcNS_11char_traitsIcEENS_9allocatorIcEEEERNS_13basic_ostreamIT_T0_EES9_RKNS_12basic_stringIS6_S7_T1_EE
  Referenced from: /Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/_t_env/lib/python2.7/site-packages/pyarrow/../../..//libarrow.0.dylib
  Expected in: flat namespace
 in /Users/travis/miniconda3/conda-bld/pyarrow_1500346140659/_t_env/lib/python2.7/site-packages/pyarrow/../../..//libarrow.0.dylib
TESTS FAILED: pyarrow-0.5.0.pre-np111py27_2.tar.bz2
```

**Comment by wesm** [comment]
No, it looks like we're 2.3.x everywhere. @xhochy any idea what this linker issue on macOS could be?

**Comment by wesm** [comment]
Looks related to https://stackoverflow.com/questions/31149807/g-linker-issue-on-mac-os-x-undefined-symbols-for-architecture-x86-64

**Comment by xhochy** [comment]
@wesm The missing symbol looks rather like a function that should be defined in STL, I don't see any Arrow related types in there.

**Comment by wesm** [comment]
Bumped the build, hopefully we are in the clear now

**Comment by wesm** [comment]
Ugh looks like Appveyor didn't fire when arrow-cpp-feedstock master was updated! Giving it a kick...

**Comment by wesm** [comment]
Windows packages updated in anaconda.org, bumped the build again

**Comment by wesm** [comment]
Huzzah! @bmabey updated 0.5.0.pre builds should be trickling into conda-forge in the next couple hours. We'll be voting on the 0.5.0 release soon and updating again in the coming days

**Comment by bmabey** [comment]
Fantastic, thanks @wesm! On a side note, we are using `pyarrow` in production now (ATM just using it to store and read parquet files) and it is working great.

**Comment by bmabey** [comment]
@wesm I just tried the prerelease and when I try to load up a parquet file saved with `0.4.1` I get a `Segmentation fault: 11`. The parquet files should be backwards compatible shouldn't they?

**Comment by wesm** [comment]
I think the parquet-cpp conda-forge package fell out of sync (we made some late ABI changes close to the release that would cause this) and needs to be updated. I will put in an update this evening

**Comment by wesm** [comment]
https://github.com/conda-forge/parquet-cpp-feedstock/pull/29

**Pull request merged**
