### PR TITLE
Update to 0.4.0 release, enable Parquet on Windows

### PR DESCRIPTION
**Pull request by jreback**
cc @wesm

the package looks good, just recipe needs updating.

### CODE REVIEW

**Comment by wesm** [comment]
You need to add `--with-parquet` to the `bld.bat`. That will fail until parquet-cpp-feedstock is updated to pick up PARQUET-992 https://github.com/apache/parquet-cpp/commit/6787492eccef3ba6ff891a6dad4f32ba09d268e7

**Comment by wesm** [comment]
This also needs https://github.com/apache/arrow/commit/fee44751048847ce1e08039ab72c09918b11b31b merged earlier today

**Comment by wesm** [comment]
I'm going to push a parquet-cpp update with the RC0 tag

**Comment by jreback** [comment]
done

**Comment by wesm** [comment]
Like I said, the build is going to fail until the parquet-cpp packages are updated.

**Comment by wesm** [comment]
As a conda-forge best practice, if you don't think a commit is going to make the build pass, it's better not to push it. The queue can sometimes be hours long (earlier this year we were sometimes waiting 12 or more hours for builds), so if you push known-bad-builds into the queue, it's just making other people's builds take longer.

**Comment by wesm** [comment]
The parquet-cpp packages are up to date now in anaconda.org. Can you bump the build hash here to the rc0 tag https://github.com/apache/arrow/tree/fea6b71468618d22ece16250ff75f23ba2f18914? Keep the version number as `0.3.0.post`; we can do a 0.4.0 release after the vote passes

**Comment by wesm** [comment]
Just updated the commit hash to HEAD, hopefully this build will pass :)

**Comment by wesm** [comment]
Ah this needs latest arrow-cpp, working on that now

**Comment by wesm** [comment]
See https://github.com/conda-forge/arrow-cpp-feedstock/pull/22. I'm also going to update parquet-cpp to include PARQUET-995

**Comment by wesm** [comment]
See also https://github.com/conda-forge/parquet-cpp-feedstock/pull/22

**Comment by wesm** [comment]
I'm in the process of updating arrow-cpp, parquet-cpp is building. I'll update this for Arrow 0.4.0 final; hopefully we'll get a passing build on Windows, then

**Comment by wesm** [comment]
I think this failed because parquet-cpp was built against an incompatible older commit of arrow-cpp, fixing that first, then will rebuild this

**Comment by wesm** [comment]
Updated the parquet-cpp build, triggered a new build here

**Comment by wesm** [comment]
Looks like maybe the parquet-cpp build was a red herring; adding snappy/brotli/thrift-cpp to `run:` Windows to see if that fixes things

**Comment by wesm** [comment]
Phew it worked. So we have some static linking problem in parquet-cpp on Windows; I will figure out what it is later and open a JIRA

**Pull request merged**
