### PR TITLE
Update to Apache Arrow 0.4.1

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@msarahan @ocefpaf @jakirkham any idea what's wrong with Appveyor here? I've never seen this error before

```
C:\bld\win-64\pyarrow-0.4.1-np111py35_vc14_0.tar.bz2
TEST START: C:\bld\win-64\pyarrow-0.4.1-np111py35_vc14_0.tar.bz2
Deleting work directory, C:\bld\pyarrow_1497299840086\work\arrow-46315431aeda3b6968b3ac4c1087f6d41052b99d
The following NEW packages will be INSTALLED:
    arrow-cpp:       0.4.1-np111py35_vc14_0  conda-forge [vc14]
    boost:           1.63.0-np111py35_vc14_6 conda-forge [vc14]
    boost-cpp:       1.63.0-vc14_2           conda-forge [vc14]
    certifi:         2017.4.17-py35_0        conda-forge
    mkl:             2017.0.1-0              defaults   
    numpy:           1.11.3-py35_0           defaults   
    pandas:          0.20.2-np111py35_1      conda-forge
    parquet-cpp:     1.2.0.pre-vc14_0        conda-forge [vc14]
    pyarrow:         0.4.1-np111py35_vc14_0  local       [vc14]
    python:          3.5.3-3                 conda-forge
    python-dateutil: 2.6.0-py35_0            conda-forge
    pytz:            2017.2-py35_0           conda-forge
    setuptools:      33.1.1-py35_0           conda-forge
    six:             1.10.0-py35_1           conda-forge
    vc:              14-0                    conda-forge
    vs2015_runtime:  14.0.25420-0            conda-forge
    wincertstore:    0.2-py35_0              conda-forge
    zlib:            1.2.11-vc14_0           conda-forge [vc14]
WARNING: conda-build appears to be out of date. You have version 2.1.10 but the
latest version is 2.1.15. Run
conda update -n root conda-build
to get the latest version.
(root) C:\bld\pyarrow_1497299840086\test_tmp>call "C:\Miniconda35-x64\Scripts\activate.bat" "C:\bld\pyarrow_1497299840086\_t_env"  1>nul 2>&1 
(root) C:\bld\pyarrow_1497299840086\test_tmp>if errorlevel 1 exit 1 
TESTS FAILED: pyarrow-0.4.1-np111py35_vc14_0
Command exited with code 1
```

**Comment by wesm** [comment]
Here's an old thread that seems similar https://groups.google.com/a/continuum.io/forum/#!topic/conda/G78CnLD_g2k

**Comment by jakirkham** [comment]
`conda` recently got updated. It is possible that the package is broken. If so, we might need to pull it.

**Comment by jakirkham** [comment]
Another option would be to simply pin `conda` on Windows in `conda-forge-build-setup`. This would allow the package to remain, but fix the breakage on AppVeyor for the moment.

**Comment by wesm** [comment]
OK, what's a known good conda version?

**Comment by jakirkham** [comment]
We were using 4.2.13 last. Though I'm looking at `conda` package and am not seeing anything that indicates it's broken. 😕

Right now I'm trying to fix up staged-recipes, which also has been impacted. If you have a minute to spare, would you mind doing a PR to `conda-forge-build-setup`? Basically we need to pin `conda` in the batch file in that recipe, which should workaround the issue for the interim.

**Comment by msarahan** [comment]
That might be conda - certainly worth trying the older version.

FWIW, conda-build's test suite has been running against conda 4.3.21 for quite a while without issue, so it could also be something else.

**Comment by wesm** [comment]
Let me know what I can try to do. I'd really like to get this package out

**Comment by jakirkham** [comment]
Back looking at this. Will let you know when I have something concrete.

**Comment by jakirkham** [comment]
Have added PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/70 ), which should bring us back to a working `conda` version on Windows. Will need to investigate this problem further to find the root cause, but need to restore some level of stability first.

**Comment by jakirkham** [comment]
So have pinned `conda` to 4.2.13 on Windows. Also have restarted the AppVeyor build here. Based on some brief testing with `conda-forge-build-setup` and another feedstock, it looks like the workaround should address the issue. Looking into potential causes.

**Comment by wesm** [comment]
Thank you for the help =)

**Pull request merged**
